fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [-i]
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
        args: [-I./include, -std=c++20]
